In [22]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset1 =pd.read_csv('D:/features/combine.csv')

#removing duplicacy from features






D:\python\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [23]:
dataset11=dataset1[dataset1.duplicated('bookingID')]

In [24]:
#calculating the mean

In [25]:
dataset1=dataset1.groupby('bookingID').median()

In [20]:
dataset1

Accuracy     Bearing  acceleration_x  acceleration_y  \
bookingID                                                           
0              8.0000  145.149109       -0.762709       -9.610388   
1              4.0000  110.000000       -0.555608        9.532810   
2              3.6360  235.000000        0.395055        9.823709   
4             10.0000  134.263748       -0.388869       -9.380925   
6              4.0000  258.000000        0.466884        9.569917   
7              3.9000   57.000000        1.393000        9.377000   
8              5.9880  202.000000       -1.100677        9.398682   
10             3.9000  113.000000        0.925354        9.312241   
11             3.9500  124.000000        0.524346        9.754276   
13             6.0000  247.000000        1.022355        8.705584   
14            16.0000  156.779297       -0.293539       -9.740111   
16             3.9000  120.000000        1.240196        9.737817   
17             3.9000   95.000000        2.804807        9.313444   
18            10.0000  186.777847        0.105423       -9.792523   
21             4.0000  103.000000        0.322020        9.235633   
25             6.0000  237.000000       -0.603339        8.868123   
26             4.0000  294.000000       -0.493221        9.857229   
27            11.0000   74.000000        0.200514        9.501390   
28             3.9000  112.500000       -0.080208        9.668081   
29             4.5510   51.500000        0.023689        9.971634   
30             4.5510  181.500000        0.482727        9.397659   
32             3.9000  204.000000       -0.996018        1.872323   
33             3.9000  213.000000       -0.924000       10.009000   
34             6.0000   48.000000        0.612916        9.308656   
35             5.5000  268.000000       -0.171000        9.059000   
36             3.4645  229.500000       -0.530332        9.172467   
37             3.9000  290.000000       -0.277924        9.961624   
38             3.9000   89.000000        0.252441        9.495926   
39             4.0000   77.000000        0.191542        9.754275   
41             8.0000  211.084140        0.076617        9.768641   
...               ...         ...             ...             ...   
94489280623   10.0000  145.170403       -1.214458       -4.731398   
94489280626    4.0000  182.843536       -0.357690       -9.065778   
94489280629    7.5000  230.627342        0.303334      -10.166438   
94489280630    3.9000  230.000000        1.194707       10.831368   
94489280633   18.7690  217.000000       -0.222661       10.131064   
94489280636    5.9900  166.000000        0.144849        9.752781   
94489280638    3.9000  285.000000        0.106500        8.887500   
94489280640    3.9000  288.000000       -0.542000        7.349000   
94489280641    7.0000  279.591766       -0.712241      -10.454819   
94489280648   10.0000  214.121887        0.225276       -9.759625   
94489280649   10.0000   63.430881       -0.118433       -9.520218   
94489280650    3.9000  342.000000        0.705114        9.419077   
94489280651    3.0000  218.000000       -0.162811        9.531608   
94489280657    5.3110  269.000000       -0.507586        9.620196   
94489280668   16.0000  177.999599        0.010916      -10.037762   
94489280670   18.7420    0.000000        1.932719        7.920019   
94489280672    3.5000   26.000000        0.336385        9.769540   
94489280676    5.4000  170.000000       -0.459000        8.925000   
94489280677   12.0000  120.175056       -0.008374       -9.577042   
94489280678   16.0000  191.168560        0.515077       -8.906746   
94489280681    5.0000  185.000000        4.497645       10.245102   
94489280684    6.8100  136.000000        0.461142        9.190392   
94489280685    6.7930  239.000000        0.225062        7.496474   
94489280688    3.5315   43.000000        1.643222        9.342108   
94489280689    4.0000  207.000000       -0.082911        9.707382   
94489280693

In [26]:
#reading the dataset 2
dataset2=pd.read_csv('D:/policy_singapore/safety/labels/part-00000-e9445087-aa0a-433b-a7f6-7f4c19d78ad6-c000.csv')


In [27]:
dataset2=dataset2.sort_values(by=['bookingID'])

In [28]:
#merging the datasets
dataset=pd.merge(dataset1,dataset2,on='bookingID')


In [9]:
dataset

bookingID  Accuracy     Bearing  acceleration_x  acceleration_y  \
0                  0    8.0000  145.149109       -0.762709       -9.610388   
1                  1    4.0000  110.000000       -0.555608        9.532810   
2                  2    3.6360  235.000000        0.395055        9.823709   
3                  4   10.0000  134.263748       -0.388869       -9.380925   
4                  6    4.0000  258.000000        0.466884        9.569917   
5                  7    3.9000   57.000000        1.393000        9.377000   
6                  8    5.9880  202.000000       -1.100677        9.398682   
7                 10    3.9000  113.000000        0.925354        9.312241   
8                 11    3.9500  124.000000        0.524346        9.754276   
9                 13    6.0000  247.000000        1.022355        8.705584   
10                13    6.0000  247.000000        1.022355        8.705584   
11                14   16.0000  156.779297       -0.293539       -9.740111   
12                16    3.9000  120.000000        1.240196        9.737817   
13                17    3.9000   95.000000        2.804807        9.313444   
14                18   10.0000  186.777847        0.105423       -9.792523   
15                21    4.0000  103.000000        0.322020        9.235633   
16                25    6.0000  237.000000       -0.603339        8.868123   
17                26    4.0000  294.000000       -0.493221        9.857229   
18                27   11.0000   74.000000        0.200514        9.501390   
19                28    3.9000  112.500000       -0.080208        9.668081   
20                29    4.5510   51.500000        0.023689        9.971634   
21                30    4.5510  181.500000        0.482727        9.397659   
22                32    3.9000  204.000000       -0.996018        1.872323   
23                33    3.9000  213.000000       -0.924000       10.009000   
24                34    6.0000   48.000000        0.612916        9.308656   
25                35    5.5000  268.000000       -0.171000        9.059000   
26                36    3.4645  229.500000       -0.530332        9.172467   
27                37    3.9000  290.000000       -0.277924        9.961624   
28                38    3.9000   89.000000        0.252441        9.495926   
29                39    4.0000   77.000000        0.191542        9.754275   
...              ...       ...         ...             ...             ...   
19988  1700807049403    3.7110   32.000000        0.233442        9.528016   
19989  1700807049404   10.0000  180.552155        0.481805       -9.396252   
19990  1700807049406    3.9000  160.000000        0.670380        9.631118   
19991  1700807049407    4.0000  112.000000        0.772130        8.885482   
19992  1709396983812    4.1810  125.000000        0.627300        9.160496   
19993  1709396983813   32.0000  178.578400       -7.003525       -2.051486   
19994  1709396983837    6.0000  229.000000        0.404632        9.763853   
19995  1709396983839    4.5135  181.000000        0.187951        6.917060   
19996  1709396983864   10.0000  262.098694        0.195818       -8.997290   
19997  1709396983889    8.0000  147.000000       -0.247501        9.146149   
19998  1709396983894    8.0000  204.907516       -0.302960       -9.754092   
19999  1709396983896   12.0000  292.287384       -0.680763       -9.139050   
20000  1709396983900    4.0000   97.500000        0.342309       -3.011982   
20001  1709396983901    4.0000   87.000000        0.694864        9.497903   
20002  1709396983904    4.0000  105.000000       -0.112527        9.845556   
20003  1709396983905   10.0000  282.790283        1.003387       -8.839230   
20004  1709396983906    3.3260  197.000000        0.990002        9.610326   
20005  1709396983907   10.0000  225.902557       -0.058543       -8.083325   
20006  1709396983911    5.0000  214.062469        0.738559       -9.467656   
20007  1709396983917    7.6800  1

In [33]:
#splitting the dataset
X = dataset.iloc[:, 0:11].values
y = dataset.iloc[:, 11].values

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,random_state=153)
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
y_train=y_train.reshape(-1, 1)
sc_y = StandardScaler()
y_train = sc_y.fit_transform(y_train)

# Fitting Decision Tree Regression to the dataset
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state =0)
regressor.fit(X_train, y_train)



DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=0, splitter='best')

In [31]:
X_test

array([[ 1.63523829, -0.10591262,  1.13184554, ...,  0.02888695,
         1.2085037 ,  2.36886472],
       [ 0.59340015,  0.04148986, -0.5997624 , ..., -0.58526878,
        -0.70589313, -0.83696657],
       [-1.29927249, -0.11195252,  0.46075078, ...,  0.00997723,
        -1.15200028, -0.87517455],
       ...,
       [ 1.20113907, -0.10591262,  1.23711531, ...,  0.62409763,
         1.57381979, -0.05001423],
       [ 0.0551171 , -0.10896852,  0.89498857, ...,  0.02713985,
        -0.23871005, -1.35897871],
       [-1.22981661,  0.18529714, -0.10200762, ...,  0.27571953,
        -0.10522917,  2.40838845]])

In [34]:
from sklearn.metrics import accuracy_score
# Predicting a new result
y_pred = regressor.predict(X_test)
score = accuracy_score(y_test, y_pred.round())
print(score)

0.00024975024975024975


In [30]:
y_test




array([0, 1, 0, ..., 1, 0, 0], dtype=int64)

array([0., 0., 0., ..., 1., 1., 0.])

In [31]:
y_pred

array([0., 1., 0., ..., 1., 0., 0.])